<h2>Terms of Service</h2>                                                                                                                                                                                                                                                      
<p>                                                                                                                                                                                                                                                                            
        This website is provided as-is with no warranty or guarantee.  Use of this                                                                                                                                                                                             
        website is at one's own discretion and implies agreement to this terms of                                                                                                                                                                                              
        service and privacy policy.                                                                                                                                                                                                                                            
</p>                                                                                                                                                                                                                                                                           
<p>                                                                                                                                                                                                                                                                            
        All content on this website is &copy; <?php echo date('Y'); ?> Humble Software                                                                                                                                                                                         
        Development unless otherwise stated.                                                                                                                                                                                                                                   
</p>                                                                                                                                                                                                                                                                           
<h2>Privacy Policy</h2>                                                                                                                                                                                                                                                        
<p>                                                                                                                                                                                                                                                                            
        All data collected is considered confidential and will be kept private.                                                                                                                                                                                                
</p>                                                                                                                                                                                                                                                                           
<h3>Data Collected</h3>                                                                                                                                                                                                                                                        
<p>
        This website may collect data from user interaction with the site.
        This site uses Google Analytics to collect additional 
        statistics.
</p>
