embed_assets: off
compress_assets: on

codemirrir: &codemirror
  - lib/codemirror/lib/codemirror.js
  - lib/codemirror/mode/javascript/javascript.js
  - lib/codemirror/mode/htmlmixed/htmlmixed.js
  - lib/codemirror/mode/css/css.js
  - lib/codemirror/mode/xml/xml.js
  - lib/flotr2/examples/lib/beautify.js
  - lib/flotr2/examples/lib/randomseed.js

envision-deps: &envision-deps
  - lib/flotr2/lib/bean.js
  - lib/flotr2/lib/underscore.js
  - lib/flotr2/js/Flotr.js
  - lib/flotr2/js/DefaultOptions.js
  - lib/flotr2/js/Color.js
  - lib/flotr2/js/Date.js
  - lib/flotr2/js/DOM.js
  - lib/flotr2/js/EventAdapter.js
  - lib/flotr2/js/Graph.js
  - lib/flotr2/js/Axis.js
  - lib/flotr2/js/Series.js
  - lib/flotr2/js/Text.js
  - lib/flotr2/js/types/lines.js
  - lib/flotr2/js/types/bars.js
  - lib/flotr2/js/types/points.js
  - lib/flotr2/js/plugins/selection.js
  - lib/flotr2/js/plugins/legend.js
  - lib/flotr2/js/plugins/hit.js
  - lib/flotr2/js/plugins/labels.js
  - lib/flotr2/js/plugins/legend.js
  - lib/flotr2/js/plugins/titles.js
  - lib/envision/lib/bonzo/bonzo.min.js

envision: &envision
  - lib/envision/js/license.js
  - lib/envision/js/Envision.js
  - lib/envision/js/Visualization.js
  - lib/envision/js/Component.js
  - lib/envision/js/Interaction.js
  - lib/envision/js/Preprocessor.js
  - lib/envision/js/actions/namespace.js
  - lib/envision/js/actions/hit.js
  - lib/envision/js/actions/selection.js
  - lib/envision/js/actions/zoom.js
  - lib/envision/js/adapters/namespace.js
  - lib/envision/js/adapters/flotr/namespace.js
  - lib/envision/js/adapters/flotr/defaultOptions.js
  - lib/envision/js/adapters/flotr/Child.js
  - lib/envision/js/adapters/flotr/lite-lines.js
  - lib/envision/js/adapters/flotr/whiskers.js
  - lib/envision/js/components/namespace.js
  - lib/envision/js/components/QuadraticDrawing.js
  - lib/envision/js/templates/namespace.js
  - lib/envision/js/templates/Finance.js
  - lib/envision/js/templates/TimeSeries.js
  - lib/envision/js/templates/Zoom.js

javascripts:

  js/hsd:
    - lib/jquery/jquery-1.7.1.min.js
    - lib/google-code-prettify/prettify.js
    - *codemirror
    - js/HSD.js

  js/hsd-ie8:
    - lib/flotr2/flotr2.ie.min.js

  js/projects:
    # envision
    - lib/flotr2/flotr2.min.js
    - lib/flotr2/js/plugins/handles.js
    - lib/envision/lib/bonzo/bonzo.min.js
    - *envision
    # finance demo
    - lib/envision/demos/data/data.js
    - js/envision/demos/finance.js
    # flotr
    - lib/flotr2/flotr2.examples.types.js
    - js/projects.js

  js/demos-trig:
    - js/demos/Trig.js
    - js/demos/TrigDemo.js

  js/demos-trig-d3:
    - js/d3.min.js
    - js/demos/trig-d3.js

  js/demos-fortune:
    - js/d3.min.js
    - js/demos/f500.min.js
    - js/demos/fortune.js

  js/hsd-flotr2:
    - lib/flotr2/flotr2.js
  js/hsd-flotr2-documentation:
    - lib/flotr2/flotr2.examples.types.js
    - lib/flotr2/examples/js/Editor.js
    - js/flotr2/documentation.js

  js/hsd-envision:
    - *envision-deps
    - *envision
    - lib/flotr2/examples/js/Editor.js
  js/hsd-envision-demos:
    - js/envision/demos.js
    - js/envision/demos/timeseries.js
    - js/envision/demos/finance.js
    - js/envision/demos/custom.js
    - js/envision/demos/fractal.js
    - lib/envision/demos/data/data.js
    - js/envision/demos/ajax.js
  js/hsd-envision-demo:
    - lib/flotr2/js/plugins/handles.js
    - js/envision/demos.js
    - lib/envision/demos/data/data.js
  js/hsd-envision-documentation:
    - js/envision/documentation.js

  js/envision/ajax-demo-initial-data:
    - lib/envision/demos/data/initial.json
  js/envision/ajax-demo-dynamic-data:
    - lib/envision/demos/data/ajax.json

stylesheets:

  css/hsd:
    - css/styles.css
    - css/button.css
    - lib/google-code-prettify/prettify.css

  css/projects:
    - lib/envision/envision.css

  css/demos:
    - css/demos.css
    - css/demos/trig-d3.css
    - css/demos/fortune.css

  css/hsd-flotr2:
    - lib/codemirror/lib/codemirror.css
    - lib/flotr2/examples/editor.css
    - lib/flotr2/examples/examples.css
    - css/flotr.css
    - css/flotr_examples.css
    - css/documentation.css

  css/hsd-envision:
    - lib/flotr2/examples/editor.css
    - lib/codemirror/lib/codemirror.css
    - lib/envision/envision.css
    - css/documentation.css
    - css/envision/editor.css
    - css/envision/demos.css
    - css/envision/documentation.css

  css/helloreddit:
    - css/helloreddit.css

  css/helloreddit-blackberry:
    - css/helloreddit-blackberry.css
